default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  username: <%= ENV['BUT_WHY_THO_DB_USER'] %>
  password: <%= ENV['BUT_WHY_THO_DB_ACCESS'] %>
  host: localhost

development:
  <<: *default
  database: but_why_tho_development

test:
  <<: *default
  database: but_why_tho_test

production:
  <<: *default
  database: but_why_tho_production
